ratings:
  paths:
  - "src/**.js"

plugins:
  eslint:
    enabled: true
    config:
      config: /.eslintrc
  fixme:
    enabled: true
  nodesecurity:
    enabled: true

exclude_paths:
  - "test/**"
  - "src/**/*.spec.js"
