version: '3'
services:

  database:
    image: 'mongo'
    container_name: 'database'
    ports:
      - '27017-27019:27017-27019'
  queue:
    image: 'rabbitmq'
    container_name: 'queue'
    ports:
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  worker:
    build: .
    container_name: 'worker'
    volumes:
      - ./src:/usr/src/app/src
    links:
      - queue
      - database
    depends_on:
      - queue
      - database
    environment:
      - IS_WORKER=true
      - MONGODB_URI=mongodb://database:27017/lhd
      - SENTRY_DSN=https://776d9de9782447ae87ffbcc03d24f6ad@sentry.io/1890421
      - PORT=5001
      - WINSTON_LOG_LEVEL=debug
      - MESSAGE_QUEUE_URI=amqp://user:password@queue
      - RESTART_TIMEOUT=5000
    ports:
      - '5001:5001'
  web:
      build: .
      container_name: 'web'
      volumes:
        - ./src:/usr/src/app/src
      links:
        - queue
        - database
      depends_on:
        - worker
      environment:
        - LOGIN_PASS=Foo
        - JWT_SECRET=Foo
        - API_SECRET=Foo
        - MONGODB_URI=mongodb://database:27017/lhd
        - SENTRY_DSN=https://776d9de9782447ae87ffbcc03d24f6ad@sentry.io/1890421
        - PORT=5000
        - SHOW_ERROR_PAGES=true
        - WINSTON_LOG_LEVEL=debug
        - CONSOLE_RE_CHANNEL=
        - WEB_CONCURRENCY=1
        - MESSAGE_QUEUE_URI=amqp://user:password@queue
        - RESTART_TIMEOUT=5000
      ports:
        - '5000:5000'
