version: '3'
services:
  database:
      image: 'mongo'
      container_name: 'database'
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
      ports:
        - '27017-27019:27017-27019'
