version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'database'
    ports:
      - '27017-27019:27017-27019'
  queue:
    image: 'rabbitmq'
    container_name: 'queue'
    ports:
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  web:
      container_name: 'web'
      build:
        context: ./
        args:
          - VUE_APP_THEME=light
      links:
        - queue
        - database
      environment:
        - LOGIN_PASS=Foo
        - JWT_SECRET=Foo
        - API_SECRET=Foo
        - MONGODB_URI=mongodb://database:27017/heroku_qb9h5dc7
        - PORT=5000
        - WINSTON_LOG_LEVEL=debug
        - MESSAGE_QUEUE_URI=amqp://user:password@queue
        - SERVICE_NAME=docker
      ports:
        - '5000:5000'
