version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'database'
    ports:
      - '27017-27019:27017-27019'
  queue:
    image: 'rabbitmq'
    container_name: 'queue'
    ports:
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
