version: '3'
services:

  queue:
    image: 'rabbitmq'
    container_name: 'queue'
    ports:
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  database:
    image: 'mongo'
    container_name: 'database'
    ports:
      - '27017-27019:27017-27019'

  web:
    build: .
    container_name: 'web'
    links:
      - queue
      - database
    environment:
      - LOGIN_PASS=Foo
      - JWT_SECRET=Foo
      - MONGODB_URI=mongodb://database:27017/lhd
      - SENTRY_DSN=https://776d9de9782447ae87ffbcc03d24f6ad@sentry.io/1890421
      - PORT=5000
      - SHOW_ERROR_PAGES=true
      - WINSTON_LOG_LEVEL=debug
      - CONSOLE_RE_CHANNEL=
      - WEB_CONCURRENCY=1
      - MESSAGE_QUEUE_URI=amqp://user:password@queue
    ports:
      - '5000:5000'

  worker:
    build: .
    container_name: 'worker'
    links:
      - queue
      - database
    environment:
      - IS_WORKER=true
      - LOGIN_PASS=Foo
      - JWT_SECRET=Foo
      - MONGODB_URI=mongodb://database:27017/lhd
      - SENTRY_DSN=https://776d9de9782447ae87ffbcc03d24f6ad@sentry.io/1890421
      - PORT=5000
      - SHOW_ERROR_PAGES=true
      - WINSTON_LOG_LEVEL=debug
      - CONSOLE_RE_CHANNEL=
      - WEB_CONCURRENCY=1
      - MESSAGE_QUEUE_URI=amqp://user:password@queue
