version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'database'
    ports:
      - '27017-27019:27017-27019'
  server:
    build: .
    links:
      - database
    depends_on:
      - database
    environment:
      - LOGIN_PASS=Foo
      - JWT_SECRET=Foo
      - MONGODB_URI=mongodb://database:27017/lhd
      - SENTRY_DSN=https://776d9de9782447ae87ffbcc03d24f6ad@sentry.io/1890421
      - PORT=5000
      - SHOW_ERROR_PAGES=true
      - WINSTON_LOG_LEVEL=debug
      - CONSOLE_RE_CHANNEL=
      - WEB_CONCURRENCY=1
    ports:
      - '5000:5000'
