version: '3'
services:
  server:
    build: .
    depends_on:
      - database
    environment:
      - CIRCLE_TOKEN=992df13948558e1e264c382221a4215eabce90da
      - MONGO_DB_URL='mongodb://admin:admin@database:27017'
      - MONGO_DB_NAME=auditreports
      - PORT=5000
      - DISPLAY=:99
      - CHROME_BIN=/usr/bin/chromium-browser
    ports:
      - '5000:5000'
  database:
    image: 'mongo'
    container_name: 'database'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017-27019:27017-27019'
