version: '3'
services:
  server:
    build: .
    depends_on:
      - database
    environment:
      - LOGIN_PASS=Foo
      - JWT_SECRET=Foo
      - MONGODB_URI==mongodb://heroku_hcl19r8n:t1euolge78c1racpb4k18ecgaq@ds239578.mlab.com:39578/heroku_hcl19r8n
      - SENTRY_DSN=https://776d9de9782447ae87ffbcc03d24f6ad@sentry.io/1890421
      - PORT=5000
      - SHOW_ERROR_PAGES=true
    ports:
      - '5000:5000'
  database:
    image: 'mongo'
    container_name: 'database'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017-27019:27017-27019'
