version: '3'
services:
  proxy:
    build:
        context: .
        args:
            - CIRCLE_TOKEN=e9912f7d1465197a2509bb73bfd06b2f22b2c82a #dreipol
    ports:
      - "3000:3000"

    environment:
      - CIRCLE_TOKEN=e9912f7d1465197a2509bb73bfd06b2f22b2c82a #dreipol
